### ISSUE TITLE
Add data management functions

### ISSUE THREAD

**Issue by michaelmcd18** [metrumresearchgroup/mrgda#84]
Idea is to setup a data version tracking system as such:

Create a data-version-lookup.yaml with this as a potential setup:

```
a:
  Major: 1
  Minor: 0
  Source: sourcedatafolder
  Comments: Initial data assembly
b:
  Major: 1
  Minor: 1
  Source: sourcedatafolder
  Comments: Fixed nominal time mapping 
```
PD endpoint:
```
a:
  Major: 1
  Minor: 0
  MasterVersion: pkpd-1-0
b:
  Major: 1
  Minor: 1
  MasterVersion: pkpd-1-0
c:
  Major: 1
  Minor: 2
  MasterVersion: pkpd-1-1
```

Then add some functions to mrgda to help users pull in the most updated data and make child data sets based off a master set. 
Versioning will allow multiple child sets to use different versions of a master if needed. 
Each child data set will have its own lookup to do versioning for that endpoint. 

Potential functions to add are:
```

#' Read in latest derived data based off info in lookup
read_latest_version <- function(.lookup_path) {
  
}

#' Read in master data specified in child yaml
read_desired_master <- function(.lookup_path) {
  
}

#' Write new version of master or child data
write_latest_version <- function(.data, .spec, .lookup_path, .overwrite = FALSE) {
  # Perform check if data is being assigned same version but there are differences
  # Can allow to overwrite 
}
```
